# Generated by Django 5.2.7 on 2025-10-08 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_status', models.CharField(blank=True, choices=[('widowed', 'Widowed'), ('divorced', 'Divorced'), ('married', 'Married')], max_length=20, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('zakat_status', models.CharField(blank=True, choices=[('applicable', 'Applicable'), ('not_applicable', 'Not Applicable')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house_owned', models.BooleanField(default=False)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('terminated_on', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('current_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('last_class_passed', models.CharField(blank=True, max_length=50, null=True)),
                ('last_school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gr_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('student_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('enrollment_year', models.IntegerField(blank=True, null=True)),
                ('student_number', models.IntegerField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=10, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus')),
                ('classroom', models.ForeignKey(blank=True, help_text='Classroom where student is enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.classroom')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
