# Generated by Django 5.2.7 on 2025-10-20 10:56

import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='father_occupation',
            new_name='father_profession',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_occupation',
            new_name='guardian_profession',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_occupation',
            new_name='mother_profession',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_number',
        ),
        migrations.AddField(
            model_name='student',
            name='father_status',
            field=models.CharField(blank=True, choices=[('alive', 'Alive'), ('dead', 'Dead')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='from_year',
            field=models.IntegerField(blank=True, help_text='From year (2000-2030)', null=True, validators=[students.validators.StudentValidator.validate_year]),
        ),
        migrations.AddField(
            model_name='student',
            name='last_class_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='old_gr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sibling_in_alkhair',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='siblings_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of siblings (positive integer)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='to_year',
            field=models.IntegerField(blank=True, help_text='To year (2000-2030)', null=True, validators=[students.validators.StudentValidator.validate_year]),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address (10-500 characters)', null=True, validators=[students.validators.StudentValidator.validate_address]),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth (student must be 3-25 years old)', null=True, validators=[students.validators.StudentValidator.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number (11 digits starting with 03)', max_length=20, null=True, validators=[students.validators.StudentValidator.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(blank=True, help_text='Year of enrollment (2000-2030)', null=True, validators=[students.validators.StudentValidator.validate_year]),
        ),
        migrations.AlterField(
            model_name='student',
            name='family_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly family income in PKR', max_digits=10, null=True, validators=[students.validators.StudentValidator.validate_positive_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_cnic',
            field=models.CharField(blank=True, help_text="Father's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic]),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_contact',
            field=models.CharField(blank=True, help_text="Father's contact number (11 digits starting with 03)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_cnic',
            field=models.CharField(blank=True, help_text="Guardian's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_cnic',
            field=models.CharField(blank=True, help_text="Mother's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_contact',
            field=models.CharField(blank=True, help_text="Mother's contact number (11 digits starting with 03)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text="Student's full name", max_length=200, validators=[students.validators.StudentValidator.validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent amount in PKR', max_digits=10, null=True, validators=[students.validators.StudentValidator.validate_positive_number]),
        ),
    ]
