# Generated by Django 5.2 on 2025-10-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_grade_level'),
        ('students', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='campus',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Classroom where student is enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.classroom'),
        ),
    ]
