# Generated by Django 5.2.7 on 2025-10-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('students', '0002_rename_father_occupation_student_father_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.campus'),
        ),
    ]
