# Generated by Django 5.2.7 on 2025-10-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text="Student's shift", max_length=20, null=True),
        ),
    ]
