# Generated by Django 5.2.7 on 2025-10-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_alter_campus_library_available_and_more'),
        ('students', '0004_alter_student_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus'),
        ),
    ]
