# Generated by Django 5.2.6 on 2025-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_gr_no_student_father_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='guardians_relation',
            new_name='guardian_relation',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='duplicate_flag',
            new_name='if_duplicate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='siblings_count',
            new_name='student_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='secondary_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='current_state',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Not Active')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reason_for_transfer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='siblings_in_alkhair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='female_washrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='male_washrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
