# Generated by Django 5.2.6 on 2025-09-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_guardians_relation_student_guardian_relation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='if_duplicate',
            new_name='duplicate_flag',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_contact',
            new_name='guardian_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='composite_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='female_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='male_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='siblings_in_alkhair',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
