# Generated by Django 5.2.6 on 2025-09-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_if_duplicate_student_duplicate_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='composite_key',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='duplicate_flag',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='female_washrooms',
        ),
        migrations.RemoveField(
            model_name='student',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grades_offered_row1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grades_offered_row2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_relation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='male_washrooms',
        ),
        migrations.RemoveField(
            model_name='student',
            name='old_gr_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reason_for_transfer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='siblings_in_alkhair',
        ),
        migrations.RemoveField(
            model_name='student',
            name='siblings_names',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='to_year',
        ),
        migrations.AlterField(
            model_name='student',
            name='current_state',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Not Active')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
