# Generated by Django 5.2.6 on 2025-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_composite_key_remove_student_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_grade',
            new_name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='from_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='old_gr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reason_for_transfer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
