# Generated by Django 5.2.6 on 2025-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_current_grade_student_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
