# Generated by Django 5.2.6 on 2025-10-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_current_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='old_gr_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reason_for_transfer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='to_year',
        ),
    ]
