# Generated by Django 5.2.6 on 2025-10-01 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_campus_academic_year_end_month_and_more'),
        ('classes', '0001_initial'),
        ('students', '0010_remove_student_classroom_remove_student_from_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('campus', 'gr_no')},
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='from_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='old_gr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reason_for_transfer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='to_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_cnic',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in format: 12345-1234567-1', regex='^\\d{5}-\\d{7}-\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_contact',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid Pakistani number', regex='^(\\+92|0)?[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='gr_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='M', max_length=1),
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_number',
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2025-2026', max_length=9)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-date_enrolled'],
                'unique_together': {('student', 'classroom', 'academic_year')},
            },
        ),
    ]
