# Generated by Django 5.2.7 on 2025-11-01 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0001_initial'),
        ('students', '0005_alter_student_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBehaviourRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('source_range_start', models.DateField(blank=True, null=True)),
                ('source_range_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_behaviour_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'month')},
            },
        ),
    ]
