# Generated by Django 5.2.7 on 2025-10-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher Role',
                'verbose_name_plural': 'Teacher Roles',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('education_subjects', models.CharField(blank=True, max_length=200, null=True)),
                ('education_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_year_of_passing', models.IntegerField(blank=True, null=True)),
                ('additional_education_subjects', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_education_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_position', models.CharField(blank=True, max_length=150, null=True)),
                ('experience_from_date', models.DateField(blank=True, null=True)),
                ('experience_to_date', models.DateField(blank=True, null=True)),
                ('experience_subjects_classes_taught', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_responsibilities', models.TextField(blank=True, null=True)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('additional_institution_name_exp', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_position', models.CharField(blank=True, max_length=150, null=True)),
                ('additional_experience_from_date', models.DateField(blank=True, null=True)),
                ('additional_experience_to_date', models.DateField(blank=True, null=True)),
                ('additional_experience_subjects_classes', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_responsibilities', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('current_role_title', models.CharField(blank=True, max_length=150, null=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', help_text="Teacher's working shift", max_length=20)),
                ('current_subjects', models.CharField(blank=True, max_length=200, null=True)),
                ('current_classes_taught', models.CharField(blank=True, max_length=200, null=True)),
                ('current_extra_responsibilities', models.TextField(blank=True, null=True)),
                ('role_start_date', models.DateField(blank=True, null=True)),
                ('role_end_date', models.DateField(blank=True, null=True)),
                ('is_currently_active', models.BooleanField(default=True)),
                ('teacher_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('employee_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('save_status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Is this teacher a class teacher?')),
                ('assigned_classroom', models.OneToOneField(blank=True, help_text='Classroom assigned to this class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_teacher', to='classes.classroom')),
                ('current_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='campus.campus')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['-date_created'],
            },
        ),
    ]
