# Generated by Django 5.2.7 on 2025-10-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_coordinators',
            field=models.ManyToManyField(blank=True, help_text='Coordinators assigned to this teacher based on grades/levels taught', related_name='assigned_teachers', to='coordinator.coordinator'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_coordinator',
            field=models.ForeignKey(blank=True, help_text='LEGACY: Single coordinator (use assigned_coordinators instead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_assigned_teachers', to='coordinator.coordinator'),
        ),
    ]
