# Generated by Django 5.2.7 on 2025-10-18 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classroom_assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this teacher to classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='current_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='campus.campus'),
        ),
    ]
