# Generated by Django 5.2.7 on 2025-10-07 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_fix_teacher_assignments'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='assigned_classroom',
            field=models.OneToOneField(blank=True, help_text='Classroom assigned to this class teacher (one classroom per teacher only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_teacher', to='classes.classroom'),
        ),
    ]
