# Generated by Django 5.2.6 on 2025-10-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacherexperience_teacher_and_more'),
        ('teachers', '0002_teacher_campus_teacher_joining_year_teacher_shift_and_more'),
    ]

    operations = [
    ]
