# Generated by Django 5.2 on 2025-10-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_cnic_teacher_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', help_text="Teacher's working shift", max_length=20),
        ),
    ]
