# Generated by Django 5.2.6 on 2025-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_merge_20251002_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher Role',
                'verbose_name_plural': 'Teacher Roles',
                'ordering': ['date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='joining_year',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_number',
        ),
    ]
