# Generated by Django 5.2.7 on 2025-10-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
