# Generated by Django 5.2.7 on 2025-10-16 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('teachers', '0004_teacher_classroom_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='current_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='campus.campus'),
        ),
    ]
