# Generated by Django 5.2.7 on 2025-10-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_make_permanent_address_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
