# Generated by Django 5.2 on 2025-10-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_merge_20251005_1031'),
        ('classes', '0003_alter_classroom_class_teacher_and_more'),
        ('teachers', '0004_teacher_assigned_classroom_teacher_is_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='assigned_classroom',
            field=models.ForeignKey(blank=True, help_text='Classroom assigned to this class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_teacher', to='classes.classroom', unique=True),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('is_class_teacher', True)), fields=('assigned_classroom',), name='unique_class_teacher_per_classroom'),
        ),
    ]
