# Generated by Django 5.2.7 on 2025-10-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_make_cnic_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_grade',
            field=models.CharField(blank=True, help_text='Grade for class teacher assignment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_section',
            field=models.CharField(blank=True, help_text='Section for class teacher assignment', max_length=10, null=True),
        ),
    ]
