# Generated by Django 5.2 on 2025-10-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classroom_unique_classroom_per_teacher_and_more'),
        ('teachers', '0005_alter_teacher_assigned_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacher',
            name='unique_class_teacher_per_classroom',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_classroom',
            field=models.OneToOneField(blank=True, help_text='Classroom assigned to this class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_teacher', to='classes.classroom'),
        ),
    ]
