# Generated by Django 5.0.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_fix_teacher_assignments'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_coordinator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_teachers',
                to='coordinator.coordinator',
                verbose_name='Assigned Coordinator'
            ),
        ),
    ]
