# Generated by Django 5.2.7 on 2025-10-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_add_class_teacher_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='additional_education_grade',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_education_level',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_education_subjects',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_experience_subjects_classes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_institution_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_responsibilities',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_year_of_passing',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience_from_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience_subjects_classes_taught',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience_to_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='role_end_date',
        ),
    ]
