# Generated by Django 5.2.7 on 2025-10-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0006_alter_coordinator_options_and_more'),
        ('teachers', '0006_remove_teacher_unique_class_teacher_per_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_coordinator',
            field=models.ForeignKey(blank=True, help_text='Coordinator assigned to this teacher based on grade/level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='coordinator.coordinator'),
        ),
    ]
