# Generated by Django 5.2.7 on 2025-10-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_remove_teacher_additional_education_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='additional_experience_from_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_experience_to_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_institution_name_exp',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='additional_position',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='previous_responsibilities',
        ),
    ]
