# Generated by Django 5.2.7 on 2025-10-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_remove_teacher_additional_experience_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
