# Generated by Django 5.2.7 on 2025-10-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teacher_experience_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='current_role_title',
        ),
    ]
