# Generated by Django 5.2.7 on 2025-10-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_remove_teacher_current_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='current_role_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
