# Generated by Django 5.2.7 on 2025-10-21 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_level_unique_together_level_shift_and_more'),
        ('teachers', '0011_teacher_current_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_level',
            field=models.ForeignKey(blank=True, help_text='Level for class teacher assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='classes.level'),
        ),
    ]
