# Generated by Django 5.2.7 on 2025-10-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classroom_shift_alter_level_shift'),
        ('teachers', '0012_add_class_teacher_level_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_classrooms',
            field=models.ManyToManyField(blank=True, help_text='Classrooms assigned to this class teacher (can be multiple for both shifts)', related_name='class_teachers', to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_classroom',
            field=models.OneToOneField(blank=True, help_text='LEGACY: Single classroom assignment (use assigned_classrooms instead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_class_teacher', to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', help_text="Teacher's working shift", max_length=20),
        ),
    ]
