# Generated by Django 5.2 on 2025-10-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('permanent_address', models.TextField()),
                ('education_level', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('total_experience_years', models.PositiveIntegerField()),
                ('joining_date', models.DateField()),
                ('is_currently_active', models.BooleanField(default=True)),
                ('can_assign_class_teachers', models.BooleanField(default=True, help_text='Can this coordinator assign class teachers?')),
                ('employee_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_set', to='classes.level')),
            ],
        ),
    ]
