# Generated by Django 5.2.6 on 2025-10-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_remove_campus_campus_address_and_more'),
        ('classes', '0001_initial'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='phone',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='coordinator',
            old_name='is_active',
            new_name='is_currently_active',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='education_level',
            field=models.CharField(default='Bachelor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='employee_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='institution_name',
            field=models.CharField(default='Temporary Institution', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='joining_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='permanent_address',
            field=models.TextField(default='Temporary Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='total_experience_years',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='year_of_passing',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.level'),
        ),
    ]
