# Generated by Django 5.2.7 on 2025-10-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'),  ('both', 'Morning + Afternoon'), ('all', 'All Shifts')], default='both', help_text='Shift(s) this coordinator manages', max_length=20),
        ),
    ]
