# Generated by Django 5.2.7 on 2025-10-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classroom_shift_alter_level_shift'),
        ('coordinator', '0002_coordinator_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='assigned_levels',
            field=models.ManyToManyField(blank=True, help_text='Levels managed by this coordinator when shift is both', related_name='assigned_coordinators', to='classes.level'),
        ),
    ]
