# Generated by Django 5.2 on 2025-10-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_rename_phone_coordinator_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
