# Generated by Django 5.2 on 2025-10-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_alter_coordinator_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='can_assign_class_teachers',
            field=models.BooleanField(default=True, help_text='Can this coordinator assign class teachers?'),
        ),
    ]
