# Generated by Django 5.2 on 2025-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_merge_20251005_1031'),
        ('classes', '0003_alter_classroom_class_teacher_and_more'),
        ('coordinator', '0004_coordinator_can_assign_class_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coordinator', 'verbose_name_plural': 'Coordinators'},
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(fields=('campus', 'level'), name='unique_coordinator_per_campus_level'),
        ),
    ]
