# Generated by Django 5.2 on 2025-10-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classroom_unique_classroom_per_teacher_and_more'),
        ('coordinator', '0005_alter_coordinator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='coordinator',
            name='unique_coordinator_per_campus_level',
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_set', to='classes.level'),
        ),
    ]
