# Generated by Django 5.2.6 on 2025-10-04 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0004_remove_campus_campus_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('permanent_address', models.TextField()),
                ('education_level', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('total_experience_years', models.PositiveIntegerField()),
                ('joining_date', models.DateField()),
                ('is_currently_active', models.BooleanField(default=True)),
                ('employee_code', models.CharField(editable=False, max_length=20, unique=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
            ],
        ),
    ]
