# Generated by Django 5.2.7 on 2025-10-16 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('principals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus'),
        ),
    ]
