# Generated by Django 5.2.6 on 2025-10-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='employee_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, null=True, unique=True),
        ),
    ]
