# Generated by Django 5.2 on 2025-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_merge_20251005_1031'),
        ('principals', '0002_alter_principal_employee_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Principal', 'verbose_name_plural': 'Principals'},
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(fields=('campus',), name='unique_principal_per_campus'),
        ),
    ]
