# Generated by Django 5.2.7 on 2025-10-27 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('principals', '0003_alter_principal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='principal',
            name='unique_principal_per_campus',
        ),
        migrations.AlterField(
            model_name='principal',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both'), ('all', 'All Shifts')], default='morning', help_text="Principal's working shift", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(fields=('campus', 'shift'), name='unique_principal_per_campus_shift'),
        ),
    ]
