# Generated by Django 5.2.7 on 2025-10-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principals', '0003_alter_principal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='shift',
            field=models.CharField(
                choices=[
                    ('morning', 'Morning'),
                    ('afternoon', 'Afternoon'),
                    ('evening', 'Evening'),
                    ('both', 'Morning + Afternoon'),
                    ('all', 'All Shifts'),
                ],
                default='morning',
                help_text="Principal's working shift",
                max_length=20,
            ),
        ),
    ]
