# Generated by Django 5.2.7 on 2025-10-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principals', '0004_add_shift_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
