# Generated by Django 5.2.7 on 2025-10-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcomplaint',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='requestcomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests.requestcomplaint'),
        ),
        migrations.AddField(
            model_name='requeststatushistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests.requestcomplaint'),
        ),
    ]
