# Generated by Django 5.2.7 on 2025-11-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekend',
            name='date',
            field=models.DateField(),
        ),
    ]
