# Generated by Django 5.2.7 on 2025-10-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='archived_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='replaced_by_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
