# Generated by Django 5.2.7 on 2025-10-18 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(choices=[('termination', 'Termination'), ('transfer', 'Transfer'), ('leaving', 'Leaving')], max_length=20)),
                ('reason', models.CharField(choices=[('expelled', 'Expelled'), ('withdrawn', 'Withdrawn'), ('academic_dismissal', 'Academic Dismissal'), ('transfer_abroad', 'Transfer Abroad'), ('parent_request', 'Parent Request'), ('other', 'Other')], max_length=50)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('date_of_request', models.DateField(default=django.utils.timezone.now)),
                ('date_of_effect', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Exit Record',
                'verbose_name_plural': 'Student Exit Records',
                'ordering': ('-created_at',),
            },
        ),
    ]
