# Generated by Django 5.2.7 on 2025-10-17 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0005_alter_teacher_current_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('student', 'Student Transfer'), ('teacher', 'Teacher Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('from_shift', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1)),
                ('to_shift', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='campus.campus')),
                ('receiving_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requesting_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('to_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='campus.campus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('old_id', models.CharField(max_length=50)),
                ('old_campus_code', models.CharField(max_length=10)),
                ('old_shift', models.CharField(max_length=1)),
                ('old_year', models.CharField(max_length=2)),
                ('new_id', models.CharField(max_length=50)),
                ('new_campus_code', models.CharField(max_length=10)),
                ('new_shift', models.CharField(max_length=1)),
                ('new_year', models.CharField(max_length=2)),
                ('immutable_suffix', models.CharField(max_length=20)),
                ('change_reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_history', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_history', to='teachers.teacher')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_changes', to='transfers.transferrequest')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status'], name='transfers_t_status_9a4f24_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['request_type'], name='transfers_t_request_5daa60_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['from_campus', 'to_campus'], name='transfers_t_from_ca_d92d62_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['requesting_principal', 'receiving_principal'], name='transfers_t_request_1883f9_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['entity_type'], name='transfers_i_entity__64bccd_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['old_id'], name='transfers_i_old_id_637d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['new_id'], name='transfers_i_new_id_bdb666_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['student', 'teacher'], name='transfers_i_student_4fdae5_idx'),
        ),
    ]
