# Generated by Django 5.2.7 on 2025-10-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('old_id', models.CharField(max_length=50)),
                ('old_campus_code', models.CharField(max_length=10)),
                ('old_shift', models.CharField(max_length=1)),
                ('old_year', models.CharField(max_length=2)),
                ('new_id', models.CharField(max_length=50)),
                ('new_campus_code', models.CharField(max_length=10)),
                ('new_shift', models.CharField(max_length=1)),
                ('new_year', models.CharField(max_length=2)),
                ('immutable_suffix', models.CharField(max_length=20)),
                ('change_reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('student', 'Student Transfer'), ('teacher', 'Teacher Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('from_shift', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1)),
                ('to_shift', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
