# Generated by Django 5.2.7 on 2025-10-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='from_shift',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_shift',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1),
        ),
    ]
