# Generated by Django 5.2.7 on 2025-10-18 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0002_initial'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idhistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idhistory',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_history', to='students.student'),
        ),
        migrations.AddField(
            model_name='idhistory',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_history', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='from_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='receiving_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requesting_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='to_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='idhistory',
            name='transfer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_changes', to='transfers.transferrequest'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status'], name='transfers_t_status_9a4f24_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['request_type'], name='transfers_t_request_5daa60_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['from_campus', 'to_campus'], name='transfers_t_from_ca_d92d62_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['requesting_principal', 'receiving_principal'], name='transfers_t_request_1883f9_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['entity_type'], name='transfers_i_entity__64bccd_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['old_id'], name='transfers_i_old_id_637d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['new_id'], name='transfers_i_new_id_bdb666_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['student', 'teacher'], name='transfers_i_student_4fdae5_idx'),
        ),
    ]
