# Generated by Django 5.2.7 on 2025-10-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_alter_campus_library_available_and_more'),
        ('transfers', '0003_alter_idhistory_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='from_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='campus.campus'),
        ),
    ]
