# Generated by Django 5.2.5 on 2025-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('temporary_closed', 'Temporary Closed')], default='active', max_length=20)),
                ('governing_body', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_no', models.CharField(blank=True, help_text='Official campus registration or license number', max_length=100, null=True)),
                ('address', models.TextField()),
                ('grades_offered', models.CharField(help_text='e.g. Grade 1 - Grade 12', max_length=255)),
                ('languages_of_instruction', models.CharField(help_text='e.g. English, Urdu', max_length=255)),
                ('academic_year_start', models.DateField()),
                ('academic_year_end', models.DateField()),
                ('capacity', models.PositiveIntegerField(help_text='Maximum student capacity')),
                ('classes_per_grade', models.PositiveIntegerField(default=0)),
                ('avg_class_size', models.PositiveIntegerField(default=0)),
                ('num_students', models.PositiveIntegerField(default=0, help_text='Total students')),
                ('num_students_male', models.PositiveIntegerField(default=0, help_text='Number of male students')),
                ('num_students_female', models.PositiveIntegerField(default=0, help_text='Number of female students')),
                ('num_teachers', models.PositiveIntegerField(default=0, help_text='Total teachers')),
                ('num_teachers_male', models.PositiveIntegerField(default=0, help_text='Number of male teachers')),
                ('num_teachers_female', models.PositiveIntegerField(default=0, help_text='Number of female teachers')),
                ('num_rooms', models.PositiveIntegerField(default=0)),
                ('total_classrooms', models.PositiveIntegerField(default=0)),
                ('office_rooms', models.PositiveIntegerField(default=0, help_text='Number of office rooms')),
                ('biology_labs', models.PositiveIntegerField(default=0)),
                ('chemistry_labs', models.PositiveIntegerField(default=0)),
                ('physics_labs', models.PositiveIntegerField(default=0)),
                ('computer_labs', models.PositiveIntegerField(default=0)),
                ('library', models.BooleanField(default=False)),
                ('toilets_male', models.PositiveIntegerField(default=0)),
                ('toilets_female', models.PositiveIntegerField(default=0)),
                ('toilets_accessible', models.PositiveIntegerField(default=0)),
                ('toilets_teachers', models.PositiveIntegerField(default=0, help_text='Number of toilets reserved for teachers')),
                ('facilities', models.TextField(blank=True, null=True)),
                ('power_backup', models.BooleanField(default=False)),
                ('internet_wifi', models.BooleanField(default=False)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('campus_address', models.TextField(blank=True, null=True)),
                ('special_classes', models.CharField(blank=True, help_text='Special classes like Montessori, Prep Section', max_length=255, null=True)),
                ('total_teachers', models.PositiveIntegerField(default=0)),
                ('total_non_teaching_staff', models.PositiveIntegerField(default=0)),
                ('teacher_student_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('staff_contact_hr', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_office_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
