# Generated by Django 5.2 on 2025-09-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='academic_year_end',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='academic_year_start',
        ),
        migrations.AddField(
            model_name='campus',
            name='academic_year_start_month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
