# Generated by Django 5.2.7 on 2025-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='academic_year_end_month',
            field=models.CharField(blank=True, help_text="Month name e.g. 'March'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='academic_year_start_month',
            field=models.CharField(blank=True, help_text="Month name e.g. 'April'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='afternoon_female_students',
            field=models.PositiveIntegerField(default=0, help_text='Female students in afternoon shift'),
        ),
        migrations.AddField(
            model_name='campus',
            name='afternoon_female_teachers',
            field=models.PositiveIntegerField(default=0, help_text='Female teachers in afternoon shift'),
        ),
        migrations.AddField(
            model_name='campus',
            name='afternoon_male_students',
            field=models.PositiveIntegerField(default=0, help_text='Male students in afternoon shift'),
        ),
        migrations.AddField(
            model_name='campus',
            name='afternoon_male_teachers',
            field=models.PositiveIntegerField(default=0, help_text='Male teachers in afternoon shift'),
        ),
        migrations.AddField(
            model_name='campus',
            name='afternoon_total_students',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated total afternoon students'),
        ),
        migrations.AddField(
            model_name='campus',
            name='afternoon_total_teachers',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated total afternoon teachers'),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_photo',
            field=models.ImageField(blank=True, help_text='Campus photo (optional)', null=True, upload_to='campus/photos/'),
        ),
        migrations.AddField(
            model_name='campus',
            name='morning_female_students',
            field=models.PositiveIntegerField(default=0, help_text='Female students in morning shift'),
        ),
        migrations.AddField(
            model_name='campus',
            name='morning_female_teachers',
            field=models.PositiveIntegerField(default=0, help_text='Female teachers in morning shift'),
        ),
        migrations.AddField(
            model_name='campus',
            name='morning_male_students',
            field=models.PositiveIntegerField(default=0, help_text='Male students in morning shift'),
        ),
        migrations.AddField(
            model_name='campus',
            name='morning_male_teachers',
            field=models.PositiveIntegerField(default=0, help_text='Male teachers in morning shift'),
        ),
        migrations.AddField(
            model_name='campus',
            name='morning_total_students',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated total morning students'),
        ),
        migrations.AddField(
            model_name='campus',
            name='morning_total_teachers',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated total morning teachers'),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_non_teaching_staff',
            field=models.PositiveIntegerField(default=0, help_text='Total non-teaching staff'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
