# Generated by Django 5.2 on 2025-09-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_remove_campus_academic_year_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='description',
        ),
    ]
