# Generated by Django 5.2.7 on 2025-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_add_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='academic_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='academic_year_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='address_full',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_head_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campus',
            name='instruction_language',
            field=models.CharField(blank=True, help_text='e.g. English, Urdu', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='campus',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='campus',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
