# Generated by Django 5.2.7 on 2025-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_alter_campus_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='avg_class_size_male',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
