# Generated by Django 5.2.6 on 2025-10-03 09:55

from django.db import migrations, models
from django.utils import timezone
from datetime import date

def populate_campus_data(apps, schema_editor):
    """Populate new fields with data from old fields"""
    Campus = apps.get_model('campus', 'Campus')
    
    for campus in Campus.objects.all():
        # Map old fields to new fields
        campus.campus_name = campus.name or "Unnamed Campus"
        campus.campus_code = campus.code or f"CAMPUS-{campus.id:03d}"
        campus.campus_id = f"CAMPUS-{campus.id:03d}"
        campus.address_full = campus.address or "Address not provided"
        campus.instruction_language = campus.languages_of_instruction or "English"
        campus.academic_year_start = date(2025, 1, 1)
        campus.academic_year_end = date(2025, 12, 31)
        campus.postal_code = "75000"
        campus.city = "Karachi"
        campus.primary_phone = "+92-300-0000000"
        campus.official_email = f"admin{campus.id}@campus.com"
        campus.campus_head_name = "Campus Head"
        campus.grades_available = campus.grades_offered or "1,2,3,4,5"
        campus.student_capacity = campus.capacity or 100
        campus.total_students = campus.num_students or 0
        campus.male_students = campus.num_students_male or 0
        campus.female_students = campus.num_students_female or 0
        campus.total_teachers = campus.num_teachers or 0
        campus.male_teachers = campus.num_teachers_male or 0
        campus.female_teachers = campus.num_teachers_female or 0
        campus.total_classrooms = campus.total_classrooms or 0
        campus.num_computer_labs = campus.computer_labs or 0
        campus.num_science_labs = (campus.biology_labs or 0) + (campus.chemistry_labs or 0) + (campus.physics_labs or 0)
        campus.library_available = campus.library or False
        campus.internet_available = campus.internet_wifi or False
        campus.power_backup = campus.power_backup or False
        campus.male_student_washrooms = campus.toilets_male or 0
        campus.female_student_washrooms = campus.toilets_female or 0
        campus.staff_washrooms = campus.toilets_teachers or 0
        campus.registration_number = campus.registration_no or ""
        campus.is_draft = campus.is_draft or False
        
        campus.save()

def reverse_populate_campus_data(apps, schema_editor):
    """Reverse migration - not needed for this case"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_alter_campus_fields'),
    ]

    operations = [
        # Step 1: Add new fields without constraints
        migrations.AddField(
            model_name='campus',
            name='campus_id',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_name',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_type',
            field=models.CharField(choices=[('main', 'Main'), ('branch', 'Branch')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='campus',
            name='accreditation',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='instruction_language',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='academic_year_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='academic_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='address_full',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='postal_code',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='city',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='district',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='primary_phone',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='secondary_phone',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_head_name',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_head_phone',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_head_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_staff_members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='male_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='female_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_maids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_coordinators',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_guards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='other_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='male_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='female_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='student_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='morning_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='afternoon_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='shift_available',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='campus',
            name='grades_available',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_offices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_computer_labs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_science_labs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='library_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='teacher_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='canteen_facility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='meal_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='total_washrooms',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='staff_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='student_washrooms',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='male_staff_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='female_staff_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='male_student_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='female_student_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='sports_facility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='sports_available',
            field=models.TextField(blank=True, null=True),
        ),
        
        # Step 2: Populate data from old fields
        migrations.RunPython(
            code=populate_campus_data,
            reverse_code=reverse_populate_campus_data,
        ),
        
        # Step 3: Make fields required and unique
        migrations.AlterField(
            model_name='campus',
            name='campus_id',
            field=models.CharField(max_length=50, unique=True, editable=False, help_text='Auto-generated: CITY-YEAR-POSTAL-NO (e.g., KHI-16-75080-01)'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='instruction_language',
            field=models.CharField(max_length=255, help_text='e.g. English, Urdu'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='academic_year_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campus',
            name='academic_year_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campus',
            name='address_full',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campus',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='campus',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campus',
            name='primary_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='campus',
            name='official_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_head_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='grades_available',
            field=models.TextField(help_text='Comma separated e.g. Nursery, 1, 2, 3'),
        ),
        
        # Step 4: Remove old fields
        migrations.RemoveField(
            model_name='campus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='code',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='languages_of_instruction',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='academic_year_start_month',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='academic_year_end_month',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='num_students',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='num_students_male',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='num_students_female',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='num_teachers',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='num_teachers_male',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='num_teachers_female',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='grades_offered',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='biology_labs',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='chemistry_labs',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='physics_labs',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='computer_labs',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='library',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='toilets_male',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='toilets_female',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='toilets_teachers',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='internet_wifi',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='registration_no',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='total_non_teaching_staff',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='staff_contact_hr',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='admission_office_contact',
        ),
    ]
