# Generated by Django 5.2.6 on 2025-10-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_migrate_campus_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='campus_address',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='num_rooms',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='office_rooms',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='special_classes',
        ),
        migrations.AddField(
            model_name='campus',
            name='internet_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campus',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='If True, campus is in draft mode'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='sports_available',
            field=models.TextField(blank=True, help_text='If available, list sports e.g. Cricket, Football, Swimming', null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('under_construction', 'Under Construction')], default='active', max_length=20),
        ),
    ]
