# Generated by Django 5.2.6 on 2025-09-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_remove_campus_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='classes_per_grade',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='teacher_student_ratio',
        ),
    ]
