# Generated by Django 5.2.7 on 2025-10-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_campus_avg_class_size_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='avg_class_size_male',
        ),
    ]
