# Generated by Django 5.2.7 on 2025-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_make_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='grades_offered',
            field=models.TextField(blank=True, help_text='Grades offered by campus', null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='grades_available',
            field=models.TextField(blank=True, help_text='Comma separated e.g. Nursery, 1, 2, 3', null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='shift_available',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', max_length=20),
        ),
    ]
