# Generated by Django 5.2.7 on 2025-10-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_remove_campus_avg_class_size_male'),
        ('campus', '0004_remove_campus_campus_address_and_more'),
    ]

    operations = [
    ]
