# Generated by Django 5.2.7 on 2025-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_update_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='num_biology_labs',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_chemistry_labs',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_physics_labs',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
