# Generated by Django 5.2.6 on 2025-09-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_remove_campus_classes_per_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='num_rooms',
        ),
    ]
