# Generated by Django 5.2.7 on 2025-10-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_add_lab_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='female_staff_washrooms',
            new_name='female_teachers_washrooms',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='male_staff_washrooms',
            new_name='male_teachers_washrooms',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='sports_facility',
        ),
        migrations.AlterField(
            model_name='campus',
            name='staff_washrooms',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
