# Generated by Django 5.2.6 on 2025-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_remove_campus_facilities_remove_campus_num_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='classes_per_grade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='facilities',
            field=models.TextField(blank=True, help_text='Comma-separated list of facilities or JSON', null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='photo',
            field=models.TextField(blank=True, help_text='URL or data URI for campus photo', null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='teacher_student_ratio',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
