# Generated by Django 5.2.7 on 2025-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_rename_female_staff_washrooms_campus_female_teachers_washrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='library_available',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='campus',
            name='other_staff',
            field=models.PositiveIntegerField(default=0, help_text='Other non-teaching staff'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='total_coordinators',
            field=models.PositiveIntegerField(default=0, help_text='Total coordinators'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='total_guards',
            field=models.PositiveIntegerField(default=0, help_text='Total security guards'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='total_maids',
            field=models.PositiveIntegerField(default=0, help_text='Total maids/cleaning staff'),
        ),
    ]
