# Generated by Django 5.2.6 on 2025-09-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_campus_classes_per_grade_campus_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='classes_per_grade',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='teacher_student_ratio',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='toilets_accessible',
        ),
    ]
