# Generated by Django 5.2.6 on 2025-09-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_remove_campus_classes_per_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='academic_year_end_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='academic_year_start_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
