# Generated by Django 5.2.6 on 2025-10-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
        ('coordinator', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(blank=True, help_text='Class teacher for this classroom (one teacher per classroom only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classroom_teacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classes.grade'),
        ),
        migrations.AddField(
            model_name='level',
            name='campus',
            field=models.ForeignKey(help_text='Campus this level belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='level',
            name='coordinator',
            field=models.OneToOneField(blank=True, help_text='Coordinator for this level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_level_coordinator', to='coordinator.coordinator'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(help_text='Level this grade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grade_set', to='classes.level'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade', 'section')},
        ),
    ]
