# Generated by Django 5.2 on 2025-10-06 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0004_teacher_assigned_classroom_teacher_is_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher assigned to this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_assigned', to='teachers.teacher'),
        ),
    ]
