# Generated by Django 5.2.6 on 2025-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='grade',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('grades', models.ManyToManyField(blank=True, related_name='levels', to='classes.grade')),
            ],
        ),
    ]
