# Generated by Django 5.2.7 on 2025-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='level',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'),  ('both', 'Morning + Afternoon'), ('all', 'All Shifts')], default='morning', help_text='Shift for this level', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('campus', 'name', 'shift')},
        ),
    ]
