# Generated by Django 5.2.7 on 2025-10-07 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(blank=True, help_text='Class teacher for this classroom (one teacher per classroom only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classroom_teacher', to='teachers.teacher'),
        ),
    ]
