# Generated by Django 5.2.6 on 2025-10-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('campus', 'name')},
        ),
    ]
