# Generated by Django 5.2 on 2025-10-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classroom_class_teacher'),
        ('teachers', '0004_teacher_assigned_classroom_teacher_is_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher assigned to this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_assigned', to='teachers.teacher', unique=True),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(condition=models.Q(('class_teacher__isnull', False)), fields=('class_teacher',), name='unique_classroom_per_teacher'),
        ),
    ]
