# Generated by Django 5.2.7 on 2025-10-15 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned the class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
