# Generated by Django 5.2.7 on 2025-10-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_level_unique_together_level_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', help_text='Shift for this classroom', max_length=20),
        ),
        migrations.AlterField(
            model_name='level',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', help_text='Shift for this level', max_length=20),
        ),
    ]
