# Generated by Django 5.2.7 on 2025-10-15 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classroom_assigned_at_classroom_assigned_by'),
        ('coordinator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='coordinator_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='coordinator_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_coordinator_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='level',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Level coordinator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_level', to='coordinator.coordinator'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Pre-Primary', 'Pre-Primary'), ('Primary', 'Primary'), ('Secondary', 'Secondary')], help_text='Select educational level', max_length=50),
        ),
    ]
