# Generated by Django 5.2 on 2025-10-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_merge_20251005_1031'),
        ('classes', '0003_alter_classroom_class_teacher_and_more'),
        ('coordinator', '0005_alter_coordinator_options_and_more'),
        ('teachers', '0005_alter_teacher_assigned_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroom',
            name='unique_classroom_per_teacher',
        ),
        migrations.RemoveField(
            model_name='level',
            name='grades',
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Level this grade belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_set', to='classes.level'),
        ),
        migrations.AddField(
            model_name='level',
            name='campus',
            field=models.ForeignKey(default=1, help_text='Campus this level belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='campus.campus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='coordinator',
            field=models.OneToOneField(blank=True, help_text='Coordinator for this level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_level_coordinator', to='coordinator.coordinator'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classroom_teacher', to='teachers.teacher'),
        ),
    ]
