# Generated by Django 5.2.6 on 2025-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_grade_name_alter_level_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('both', 'Morning + Afternoon'), ('all', 'All Shifts')], default='morning', help_text='Shift for this classroom', max_length=20),
        ),
    ]
