# Generated by Django 5.2.7 on 2025-10-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_add_code_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='short_code',
        ),
        migrations.RemoveField(
            model_name='level',
            name='short_code',
        ),
    ]
