# Generated by Django 5.2.6 on 2025-10-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classroom_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ('grade__name', 'section', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade', 'section', 'shift')},
        ),
    ]
