# Generated by Django 5.2.7 on 2025-10-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_add_coordinator_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='level',
            name='coordinator_assigned_by',
        ),
    ]
