# Generated by Django 5.2.7 on 2025-10-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classroom_shift_alter_level_shift'),
        ('teachers', '0013_teacher_assigned_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher for this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_set', to='teachers.teacher'),
        ),
    ]
