# Generated by Django 5.2 on 2025-10-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classroom_unique_classroom_per_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(default=1, help_text='Level this grade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grade_set', to='classes.level'),
            preserve_default=False,
        ),
    ]
