# Generated by Django 5.2.7 on 2025-10-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True),
        ),
    ]
