# Generated by Django 5.2.7 on 2025-10-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_alter_campus_library_available_and_more'),
        ('classes', '0005_alter_classroom_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus this level belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='campus.campus'),
        ),
    ]
