# Generated by Django 5.2.7 on 2025-10-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_short_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
