# Generated by Django 5.2.7 on 2025-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_changed_default_password',
            field=models.BooleanField(default=False, help_text='Has user changed from default password?'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='When password was last changed', null=True),
        ),
    ]
