# Generated by Django 5.2.7 on 2025-10-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_password_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_changed_default_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_changed_at',
        ),
    ]
